name: RedstoneBuilder
main: me.FinnT730.redstone.RedstoneBuilder
version: 1.0
description: RedstoneBuilder
commands:
  loop:
    usage: /loopSmall
    description: This can make an circuit for you, but its is an small one....